---
title: "Project 3: Part 2"
author: "Anika Lindley"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Part 2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction

`my_rf_cv` uses cross validation to assess the predictive performance of models made using random forest.

### Installation

To install `project3package` from GitGub, run the following code in your console:

```{r, eval = FALSE}
install.packages("devtools")
devtools::install_github("anikalindley/project3package", build_vignette = TRUE, build_opts = c())
```

```{r}
library(project3package)
```

## my_rf_cv

To demonstate the use of my_rf_cv I will predict the body mass of penguins using bill length, bill dpeth, and flipper length as covariates. 

```{r}

library(reshape2)
library(ggplot2)

read.csv("../Data/my_gapminder.csv")
read.csv("../Data/my_penguins.csv")
source("../Code/my_rf_cv.R")


# matrix to store random forest cross-validation output
my_rf <- matrix(NA, 30, 3)

# iterate through k = 2, k = 5, k = 10
for (i in c(2, 5, 10)) {
  # repeat each iteration 30 times
  for(j in 1:30) {
    if (i == 2) {
      # add to column k = 2
       my_rf[j, 1] <- my_rf_cv(i)
    } else if (i == 5) {
      # add to column k = 5
       my_rf[j, 2] <- my_rf_cv(i)
    } else {
      # add to column k = 10
       my_rf[j, 3] <- my_rf_cv(i)
    }
  }
}

```

```{r}
# store my_rf as data frame
my_df <- data.frame(my_rf)
# name columns
colnames(my_df) <- c("k = 2", "k = 5", "k = 10")
# assign variable names to each value
my_df <- melt(my_df, measure.vars = c("k = 2", "k = 5", "k = 10"))

# create a boxplot for each value of k
my_plot <- ggplot(data = my_df, aes(x = variable, y = value)) + 
  geom_boxplot() + 
  theme_bw(base_size = 12) + 
  labs(x = "Number of Folds", y = "Average MSE")

# create table to store CV MSE and SD
my_table <- matrix(NA, 3, 2)
my_df2 <- data.frame(my_rf)

# average CV MSE for each value of k
my_means <- colMeans(my_df2)
# standard deviation for each value of k
my_sd <- apply(my_df2, 2, sd)

# add average CV MSE to table
my_table[, 1] <- my_means
# add standard deviation to table
my_table[, 2] <- my_sd

# add column names
colnames(my_table) <- c("Avg MSE", "SD")
# add row names
row.names(my_table) <- c("k = 2", "k = 5", "k = 10")
```

```{r}
library(readr)
# save plot to Figures folder
ggsave("../Output/Figures/my_plot.pdf", my_plot)
# save summary table to Results folder
saveRDS(my_table, "../Output/Results/my_table.rds")
# adjust column names
colnames(my_rf) <- c("k2", "k5", "k10")
# add csv file of the 90 simulated results to Results folder
write_csv(data.frame(my_rf), "../Output/Results/my_table.csv")
```
